version: "3"
services:
  directus:
    image: directus/directus:11.0.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'http://localhost:3000'
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'
      SECRET: "f73mskfhg91kmz046dneolamh"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "CaseLabJS"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"

  react:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./react-app:/app
    depends_on:
      - directus
    environment:
      CHOKIDAR_USEPOLLING: "true"